spring:
  application:
    name: orange
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orange?characterEncoding=utf8&useSSL=true
    data-username: root
    password: root
